Use SuggestGasTipCap to get GasPrice
hermeznetwork/hermez-node pull request #1032
Opened 2021-07-26 02:05 UTC by mfcastellani

### What does this PR does?

Uses SuggestGasTipCap to retrieves the currently suggested 1559 priority fee to allow a timely execution of a transaction.

### How to test?

`make test`

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [ ] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

2021-07-26 10:24 UTC, marioidival submitted a review, later dismissed

2021-07-26 11:38 UTC, jeffprestes requested changes

2021-07-26 11:38 UTC, jeffprestes commented on eth/ethereum.go
> +	return c.client.SuggestGasTipCap(ctx)
What about BaseFee? Based on other tests I've made we need to sum basefee plus the gas tip.

2021-07-27 11:43 UTC, marioidival approved these changes

2021-07-27 12:58 UTC, jeffprestes approved these changes

2021-07-27 15:15 UTC, ARR552 approved these changes

2021-07-27 15:30 UTC, arnaubennassar approved these changes

2021-07-27 18:35 UTC, merged