Reference endpoints with filter options
hermeznetwork/hermez-node pull request #1039
Opened 2021-07-27 14:36 UTC by arnaubennassar

### What does this PR does?

Add reference to the endpoint with filter options

### How to test?

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [ ] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

2021-07-27 20:00 UTC, jeffprestes requested changes

2021-07-28 07:46 UTC, arnaubennassar commented on api/swagger.yml
> +        If you want to find transactions using other filters use the endpoint `GET /transaction-pool`
I like the way you've writen it without the `you` (If you want...)

2021-07-28 08:58 UTC, jeffprestes requested changes

2021-07-28 08:58 UTC, jeffprestes commented on api/swagger.yml
> +        There are other options to filter transactions using query string parameters. Please check more details below.
I was reviewing it with @jleebee and she told me we need to change the last sentence to
```Please check for more details below```

2021-07-28 10:21 UTC, jeffprestes approved these changes

2021-07-29 14:21 UTC, merged