Improvement/http server configuration
hermeznetwork/hermez-node pull request #1110
Opened 2021-08-23 12:15 UTC by marioidival

Closes #1085 

### What does this PR does?

Add ReadTimeout/WriteTimeout API configuration into default configuration files.

### How to test?

Just waiting a bugfix from Q/A team for integration-tests repository.

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [ ] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

2021-08-24 12:44 UTC, jeffprestes approved these changes

2021-08-24 13:10 UTC, Mikelle submitted a review, later dismissed

2021-08-24 15:11 UTC, ARR552 requested changes

2021-08-24 15:11 UTC, ARR552 commented on config/config.go
> +	Writetimeout Duration `env:"HEZNODE_API_WRITETIMEOUT"`
Please add these new params to the readme:
https://github.com/hermeznetwork/hermez-node/blob/develop/config/README.md

2021-08-25 14:41 UTC, ARR552 approved these changes

2021-08-25 16:57 UTC, tclemos approved these changes

2021-08-25 16:59 UTC, merged