added checker for version in no route api
hermeznetwork/hermez-node pull request #674
Opened 2021-03-24 20:14 UTC by Mikelle

https://github.com/hermeznetwork/hermez-node/issues/665#issue-837959172

2021-03-25 11:03 UTC, arnaubennassar requested changes
I don't see when this function is called, could you add a test for this?

2021-03-25 11:22 UTC, ed255 requested changes

2021-03-25 11:22 UTC, ed255 commented on node/node.go
> +	matched, _ := regexp.MatchString(`^/v[0-9]+/`, c.Request.URL.Path)
The change looks good to me.  Nevertheless I think it's worth considering moving this logic of defining the NoRoute handler to the api module, and call the `engine.NoRoute` inside `api.NewAPI`.

2021-03-26 11:32 UTC, arnaubennassar submitted a review, later dismissed

2021-03-29 09:07 UTC, ed255 approved these changes

2021-03-29 23:14 UTC, Pantani approved these changes

2021-03-29 23:14 UTC, Pantani commented on api/api_test.go
> +const apiURL = apiIP + apiPort + "/v1/"
```suggestion
const (
	apiPort = "4010"
	apiIP   = "http://localhost:"
	apiURL  = apiIP + apiPort + "/v1/"
)
```

2021-03-31 12:01 UTC, OBrezhniev approved these changes

2021-03-31 19:54 UTC, Pantani approved these changes

2021-03-31 20:47 UTC, merged