added checker and log.warn to updateMethodTypeStatic
hermeznetwork/hermez-node pull request #676
Opened 2021-03-24 20:16 UTC by Mikelle

https://github.com/hermeznetwork/hermez-node/issues/664

2021-03-25 11:04 UTC, arnaubennassar submitted a review, later dismissed

2021-03-25 11:47 UTC, ed255 requested changes

2021-03-25 11:47 UTC, ed255 commented on priceupdater/priceupdater.go
> +				log.Warn("token price is set to 0. Probably StaticValue is not put in the configuration file")
I suggest adding the token.Symbol in the warning string to help the user determine which token price has the StaticValue at 0.

2021-03-25 12:05 UTC, Pantani approved these changes

2021-03-26 11:30 UTC, arnaubennassar approved these changes

2021-03-26 18:39 UTC, Pantani approved these changes

2021-03-29 09:09 UTC, ed255 approved these changes

2021-03-31 15:40 UTC, merged