Add package level documentation for db, historydb, l2db, api, apitype…
hermeznetwork/hermez-node pull request #683
Opened 2021-03-26 15:09 UTC by arnaubennassar

Close #679

2021-03-26 18:38 UTC, Pantani requested changes
This is a good tool to help us to avoid this typo stuffs:

https://app.grammarly.com/

2021-03-26 18:38 UTC, Pantani commented on db/historydb/historydb.go
> +- nodeinfo.go: used to handle the interfaces and structs that allow communication across running in different machines/process but sharing the same database.
```suggestion
Package historydb is responsible for storing and retrieving the historic data of the Hermez network.
It's mostly but not exclusively used by the API and the synchronizer.

Apart from the logic defined in this package, it's important to notice that there are some triggers defined in the
migration files that have to be taken into consideration to understanding the results of some queries. This especially true
for reorgs: all the data is directly or indirectly related to a block, this makes handling reorgs as easy as deleting the
reorged blocks from the block table, and all related items will be dropped in cascade. This is not the only case, in general
functions defined in this package that get affected somehow by the SQL level defined logic has a special mention on the function description.

Some of the database tooling used in this package such as meddler and migration tools is explained in the db package.

This package is spitted in different files following these ideas:
- historydb.go: constructor and functions used by packages other than the api.
- apiqueries.go: functions used by the API, the queries implemented in this functions use a semaphore
to restrict the maximum concurrent connections to the database.
- views.go: structs used to retrieve/store data from/to the database. When possible, the common structs are used, however
most of the time there is no 1:1 relation between the struct fields and the tables of the schema, especially when joining tables.
In some cases, some of the structs defined in this file also include custom Marshallers to easily match the expected api formats.
- nodeinfo.go: used to handle the interfaces and structs that allow communication across running in different machines/process but sharing the same database.
```

2021-03-26 18:38 UTC, Pantani commented on db/utils.go
> +- Custom meddlers: used to easily transform struct <==> table
```suggestion
Package db have some common utilities shared by db/l2db and db/historydb, the most relevant ones are:
- SQL connection utilities
- Managing the SQL schema: this is done using migration files placed under db/migrations. The files are executed by
order of the file name.
- Custom meddlers: used to easily transform struct <==> table
```

2021-03-26 18:38 UTC, Pantani commented on db/l2db/l2db.go
> +In some cases some of the structs defined in this file also include custom Marshallers to easily match the expected api formats.
```suggestion
Package l2db is responsible for storing and retrieving the data received by the coordinator through the api.
Note that this data will be different for each coordinator in the network, as this represents the L2 information.

The data managed by this package is fundamentally PoolL2Tx and AccountCreationAuth. All this data come from
the API sent by clients and is used by the txselector to decide which transactions are selected to forge a batch.

Some of the database tooling used in this package such as meddler and migration tools is explained in the db package.

This package is spitted in different files following these ideas:
- l2db.go: constructor and functions used by packages other than the api.
- apiqueries.go: functions used by the API, the queries implemented in this functions use a semaphore
to restrict the maximum concurrent connections to the database.
- views.go: structs used to retrieve/store data from/to the database. When possible, the common structs are used, however
most of the time there is no 1:1 relation between the struct fields and the tables of the schema, especially when joining tables.
In some cases, some of the structs defined in this file also include custom Marshallers to easily match the expected api formats.
```

2021-03-26 18:38 UTC, Pantani commented on api/stateapiupdater/stateapiupdater.go
> +of using this package.
```suggestion
Package stateapiupdater is responsible for generating and storing the object response of the GET /state endpoint exposed through the api package.
This object is extensively defined at the OpenAPI spec located at api/swagger.yml.

Deployment considerations: in a setup where multiple processes are used (dedicated api process, separated coord / sync, ...), only one process should care
of using this package.
```

2021-03-26 18:38 UTC, Pantani commented on api/api.go
> +the /config endpoint which return a static object generated at construction time, and the /state which also is retrieved from the database, but it's generated by api/stateapiupdater package.
```suggestion
Package api implements the public interface of the hermez-node using a HTTP REST API.

There are two subsets of endpoints:

- coordinatorEndpoints: used to receive L2 transactions and account creation authorizations. Targeted for wallets.
- explorerEndpoints: used to provide all sorts of information about the network. Targeted for explorers and similar services.

About the configuration of the API:

- The API is supposed to be launched using the cli found at the package cli/node, and configured through the configuration file.
- The mentioned configuration file allows exposing any combination of the endpoint subsets.
- Although the API can run in a "standalone" manner using the serveapi command, it won't work properly
unless another process acting as a coord or sync is filling the HistoryDB.

Design principles and considerations:

- In order to decouple the API process from the rest of the node, all the communication between this package and the rest of
the system is done through the SQL database. As a matter of fact, the only public function of the package is the constructor NewAPI.
All the information needed for the API to work should be obtained through the configuration file of the cli or the database.
- The format of the requests / responses doesn't match directly with the common types, and for this reason, the package api/apitypes is used
to facilitate the format conversion. Most of the time, this is done directly at the db level.
- The API endpoints are fully documented using OpenAPI fka Swagger. All the endpoints are tested against the spec to ensure consistency
between implementation and specification. To get a sense of which endpoints exist and how they work, it's strongly recommended to check this specification.
The specification can be found at api/swagger.yml.
- In general, all the API endpoints produce queries to the SQL database in order to retrieve / insert the requested information. The most notable exceptions to this are
the /config endpoint, which returns a static object generated at construction time, and the /state, which also is retrieved from the database, but it's generated by API/stateapiupdater package.
```

2021-03-29 11:01 UTC, ed255 approved these changes

2021-03-29 11:02 UTC, ed255 requested changes

2021-03-29 11:02 UTC, ed255 commented on api/api.go
> +/*
The same applies to the documentation you added to the other packages!

2021-03-29 13:52 UTC, arnaubennassar commented on api/api.go
> +/*
That was my intention, but after saving the file my formater would add this empty line :S

2021-03-29 13:55 UTC, arnaubennassar commented on api/api.go
> +- The API endpoints are fully documented using OpenAPI fka Swagger. All the endpoints are tested against the spec to ensure consistency
`fka` stands for Formerly Known As, which is more accurate than, although if this acronym is not that well known maybe it's better to go with `aka`

2021-03-29 23:11 UTC, Pantani approved these changes

2021-03-30 09:28 UTC, ed255 approved these changes

2021-03-31 10:13 UTC, ed255 approved these changes

2021-03-31 11:05 UTC, arnaucube approved these changes

2021-03-31 11:05 UTC, merged