added info if transaction is invalid
hermeznetwork/hermez-node pull request #698
Opened 2021-04-05 13:39 UTC by Mikelle

Close https://github.com/hermeznetwork/hermez-node/issues/682
Found only one place, when transacting become invalid - InvalidateOldNonces method, so only added info there.

2021-04-05 16:22 UTC, Pantani submitted a review, later dismissed

2021-04-06 10:02 UTC, ed255 approved these changes

2021-04-06 10:02 UTC, ed255 commented on db/l2db/l2db.go
> +const invalidateOldNoncesInfo = `Nonce is smaller or equal than account nonce`
I think it should just be `smaller than`. See the SQL query: `tx_pool.nonce < updated_acc.nonce;`

2021-04-06 10:05 UTC, ed255 requested changes

2021-04-06 10:05 UTC, ed255 commented on db/l2db/l2db.go
> +const invalidateOldNoncesInfo = `Nonce is smaller or equal than account nonce`
I think it should just be `smaller than`. See the SQL query: `tx_pool.nonce < updated_acc.nonce;`

2021-04-08 10:18 UTC, ed255 approved these changes

2021-04-08 21:15 UTC, Pantani approved these changes

2021-04-08 21:16 UTC, merged