added checker for toBjj address in transaction creation
hermeznetwork/hermez-node pull request #755
Opened 2021-04-27 10:35 UTC by Mikelle

Closes https://github.com/hermeznetwork/hermez-node/issues/739

### What does this PR does?

added checker for toBjj address in transaction creation

2021-04-27 17:58 UTC, jeffprestes commented on db/l2db/apiqueries.go
> +		} else if !exists {
Maybe split this if/else chain in two verifications would it make the code more clean. 
One if verifies the error
Other if, after the value is set to exists variable, check the exists variable content.

2021-04-28 11:32 UTC, Pantani requested changes
Let's wait for the answer to it:
https://github.com/hermeznetwork/hermez-node/issues/739#issuecomment-828370528

2021-04-28 13:10 UTC, jeffprestes commented
After meeting with Jordi, Carlos and Bennassar we checked the user can send tokens to a BJJ that is not already created but internally the before the hermez-node create a new account it needs to check if the account already exists and reuse it. So, this implementations needs to be made in tx-selector or batch builder and not in API. The API must accept the tx.

2021-04-30 17:51 UTC, Pantani commented
@jeffprestes @Mikelle, can we close this one?

2021-04-30 18:07 UTC, Mikelle commented
@Pantani I think yes, this pr is no longer relevant, bcs API have to accept such transactions

2021-04-30 18:07 UTC, closed without merging