Feature/merge develop with atomic tx branch
hermeznetwork/hermez-node pull request #870
Opened 2021-06-14 13:22 UTC by mfcastellani

This is a utility PR. I already fixed the conflicts in the code and just need @arnaubennassar approvation.

One important point, we have 2 migrations called 0004.sql, so since the 0004.sql from develop was already in develop I moved the 0004.sql previously in atomic-tx branch to 0005.sql. This maybe can be a issue to update my node, but is the correct path to follow.

2021-06-14 13:40 UTC, jeffprestes approved these changes

2021-06-15 11:21 UTC, arnaubennassar requested changes

2021-06-15 11:21 UTC, arnaubennassar commented on db/migrations/0005_test.go
> +	runMigrationTest(t, 4, migrationTest0005{})
```suggestion
	runMigrationTest(t, 5, migrationTest0005{})
```

2021-06-15 14:14 UTC, arnaubennassar approved these changes

2021-06-15 14:15 UTC, merged