changed token name length
hermeznetwork/hermez-node pull request #896
Opened 2021-06-24 09:18 UTC by Mikelle

Closes https://github.com/hermeznetwork/hermez-node/issues/869

### What does this PR does?

Change token name length in db

### How to test?
Run db/migrations/0005_test.go

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [ ] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

2021-06-24 11:24 UTC, mfcastellani submitted a review, later dismissed

2021-06-25 07:50 UTC, arnaubennassar requested changes

2021-06-25 07:50 UTC, arnaubennassar commented on db/migrations/0005_test.go
> +	miter.RunAssertsAfterMigrationDown(t, db)
```suggestion
	runMigrationTest(t, 5, migrationTest0005{})
```

2021-06-28 08:01 UTC, arnaubennassar requested changes

2021-06-28 08:01 UTC, arnaubennassar commented on db/migrations/0005.sql
> +ALTER TABLE token ALTER COLUMN name TYPE varchar(30);
Could you use the type `VARCHAR` (with no limits) so we avoid same problem in the future?

2021-06-28 08:36 UTC, arnaubennassar approved these changes

2021-06-29 10:00 UTC, mfcastellani approved these changes

2021-06-29 10:13 UTC, merged