Feature/gin binding and validation
hermeznetwork/hermez-node pull request #938
Opened 2021-07-05 14:47 UTC by Mikelle

Closes https://github.com/hermeznetwork/hermez-node/issues/837
### What does this PR does?

This PR moves logic from custom implementation for validation and binding to gin lib

### How to test?

Run api package tests

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [ ] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

2021-07-05 18:11 UTC, jeffprestes commented on api/parsers/coordinator.go
> +	Pagination
Is this correct ?

2021-07-05 18:16 UTC, jeffprestes requested changes
Maybe would be a nice idea left filter structs within the parsers package public to allow a third-party library to reuse them.

2021-07-05 18:16 UTC, jeffprestes commented on api/parsers/exits.go
> +type exitFilter struct {
Maybe would be a nice idea left those structs within the parsers public to allow a third-party library to reuse them.

2021-07-05 18:16 UTC, jeffprestes commented on api/parsers/fiat.go
> +type currencyFilter struct {
Maybe would be a nice idea left those structs within the parsers public to allow a third-party library to reuse them.

2021-07-05 18:16 UTC, jeffprestes commented on api/parsers/slots.go
> +type slotsFilters struct {
Maybe would be a nice idea left those structs within the parsers public to allow a third-party library to reuse them.

2021-07-06 10:22 UTC, jeffprestes approved these changes

2021-07-06 13:04 UTC, arnaubennassar approved these changes

2021-07-06 13:06 UTC, merged