Feature/api error mapping
hermeznetwork/hermez-node pull request #958
Opened 2021-07-09 10:52 UTC by Mikelle

Closes https://github.com/hermeznetwork/hermez-node/issues/627

### What does this PR does?

Expand error message object with error code and type

### How to test?

Could try to send wrong requests or run tests in api package.

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Include tests
- [ ] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

2021-07-09 11:05 UTC, jeffprestes requested changes

2021-07-09 11:05 UTC, jeffprestes commented on api/errors.go
> +	ErrSQLNoRowsCode apiErrorCode = 4
Here I think we need to add a text error message saying something such as: "record not found for this query and the parameters informed"

2021-07-09 12:34 UTC, jeffprestes requested changes

2021-07-09 12:34 UTC, jeffprestes commented on api/errors.go
> +	ErrSQLNoRows = "record not found for this query and the parameters informed"
@Mikelle , after @jleebee 's review she said the good sentence would be: ```record(s) were not found for this query and/or the parameters entered```

2021-07-09 12:43 UTC, arnaubennassar approved these changes

2021-07-09 14:21 UTC, jeffprestes approved these changes

2021-07-09 14:36 UTC, AlbertoElias commented on api/swagger.yml
> +          enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
I think it would be good to also return the string. Return an object like:

```json
{
  code: 1,
  message: 'asfdasdfasfdasdfasdf'
}
```

2021-07-09 16:09 UTC, AlbertoElias requested changes
Some comments related to the error strings

2021-07-09 16:09 UTC, AlbertoElias commented on api/swagger.yml
> +              * `ErrParamValidationFailed` - this error appears when user sending wrong info in query|uri|form params
when user sends

2021-07-09 16:09 UTC, AlbertoElias commented on api/swagger.yml
> +              * `ErrFeeOverflow` - tx with fee overflow was sent in /transactions-pool request
What does fee overflow mean?

2021-07-09 16:09 UTC, AlbertoElias commented on api/swagger.yml
> +              * `ErrAccountTokenNotEqualTxToken` - account token is not equal tx token in /transactions-pool request
not equal to

2021-07-09 16:09 UTC, AlbertoElias commented on api/swagger.yml
> +              * `ErrCantSendToEthAddr` - it's not possible to send to eth addr when there is an idx not associated to the Eth addr and token or the coordinator hasn't an authorization to create a val
it's not possible to send to Eth address when there is no account index associated to this Eth address and token, or the coordinator hasn't got an authorization to create an account

2021-07-12 07:44 UTC, arnaubennassar approved these changes

2021-07-12 07:51 UTC, krlosMata approved these changes
:smile_cat:

2021-07-12 07:55 UTC, laisolizq approved these changes

2021-07-12 10:42 UTC, AlbertoElias approved these changes

2021-07-12 10:43 UTC, merged