Feature/#765 info msg
hermeznetwork/hermez-node pull request #995
Opened 2021-07-15 09:20 UTC by ARR552

Closes #765

### What does this PR does?

This PR adds error codes and type to the info field in the tx table.

### How to test?

Run the hermez node and send an invalid tx to see the message. Also, you can run the tests to check it.

Batch forged: https://explorer.internaltestnet.hermez.io/batch/25226

## Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Include tests
- [X] Respect code style and lint
- [ ] Update swagger file (if needed)
- [ ] Update documentation (*.md) (if needed)

2021-07-16 08:22 UTC, arnaubennassar requested changes
Some suggestions:
- `common.PoolL2Tx.Info` type from `string` ==> `txSelectorError`, same for `failedAtomicGroup.reason`. Probably `txSelectorError` will need to be moved to `common` to avoid cyclic dependency
- Add columns for error type and error code in `tx_pool` table, it's inconvenient to have JSONs stored in columns
- Update object response of the API, I guess that right now it returns a string that has a JSON format for the `info` field which is inconvenient for clients

2021-07-16 12:09 UTC, marioidival approved these changes
LGTM

2021-07-19 07:35 UTC, arnaubennassar approved these changes

2021-07-19 08:19 UTC, marioidival approved these changes
LGTM

2021-07-19 08:31 UTC, arnaubennassar approved these changes

2021-07-19 08:43 UTC, merged