code owners
hermeznetwork/hermez-node pull request #998
Opened 2021-07-15 10:51 UTC by ARR552

Closes #986

### What does this PR does?

This PR adds the code owners.

2021-07-15 11:16 UTC, jeffprestes commented
This is great. However it would be defined after Hermez-Node maintainers meeting in July 30th. Until there this PR will be freeze.

2021-07-19 17:44 UTC, mfcastellani submitted a review, later dismissed

2021-08-03 07:56 UTC, arnaubennassar requested changes

2021-08-03 07:56 UTC, arnaubennassar commented on .github/CODEOWNERS
>  *.md                    @jeffprestes
```suggestion
*.md                    @jeffprestes @arnaubennassar
```

2021-08-03 07:56 UTC, arnaubennassar commented on .github/CODEOWNERS
> +txselector/             @mfcastellani @tclemos
```suggestion
txselector/             @mfcastellani @tclemos @arnaubennassar
```

2021-08-03 07:56 UTC, arnaubennassar commented on .github/CODEOWNERS
> +txprocessor/            @mfcastellani @tclemos
```suggestion
txprocessor/            @mfcastellani @tclemos @arnaubennassar
```

2021-08-03 13:46 UTC, arnaubennassar approved these changes

2021-08-05 11:43 UTC, jeffprestes approved these changes

2021-08-05 11:44 UTC, Mikelle approved these changes

2021-08-05 13:37 UTC, merged